using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Stateful.Generator;

[Generator]
public sealed class JsonPathGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Stateful.GenerateJsonPathsAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) => GetDocumentType(ctx))
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(candidates.Collect(), static (ctx, symbols) =>
        {
            foreach (var symbol in symbols.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default))
            {
                if (symbol is not null)
                {
                    ctx.AddSource($"{symbol.ToDisplayString().Replace('.', '_')}.JsonPaths.g.cs", SourceText.From(Generate(symbol), Encoding.UTF8));
                }
            }
        });
    }

    private static INamedTypeSymbol? GetDocumentType(GeneratorSyntaxContext context)
    {
        var declaration = (TypeDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(declaration) as INamedTypeSymbol;

        if (symbol is null)
        {
            return null;
        }

        return HasGenerateAttribute(symbol) ? symbol : null;
    }

    private static bool HasGenerateAttribute(INamedTypeSymbol symbol)
        => symbol.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == AttributeName);

    private static string Generate(INamedTypeSymbol document)
    {
        var namespaceName = document.ContainingNamespace.IsGlobalNamespace
            ? null
            : document.ContainingNamespace.ToDisplayString();
        var className = GetPathClassName(document);
        var documentType = document.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (namespaceName is not null)
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("public static class ").Append(className).AppendLine();
        builder.AppendLine("{");
        builder.Append("    private static readonly global::Stateful.JsonObjectPath<").Append(documentType).AppendLine("> Root = global::Stateful.JsonPath.For<").Append(documentType).AppendLine(">();");
        builder.AppendLine();

        EmitMembers(builder, document, documentType, "Root", indent: "    ", seen: ImmutableHashSet.Create<INamedTypeSymbol>(SymbolEqualityComparer.Default, document));

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string GetPathClassName(INamedTypeSymbol document)
    {
        foreach (var attribute in document.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() == AttributeName &&
                attribute.ConstructorArguments.Length == 1 &&
                attribute.ConstructorArguments[0].Value is string className &&
                !string.IsNullOrWhiteSpace(className))
            {
                return SanitizeIdentifier(className);
            }
        }

        return SanitizeIdentifier(document.Name + "Paths");
    }

    private static void EmitMembers(
        StringBuilder builder,
        INamedTypeSymbol owner,
        string documentType,
        string pathVariable,
        string indent,
        ImmutableHashSet<INamedTypeSymbol> seen)
    {
        foreach (var property in GetSerializableProperties(owner))
        {
            var jsonName = GetJsonName(property);
            var memberName = SanitizeIdentifier(property.Name);
            var propertyType = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var namedType = UnwrapNullable(property.Type) as INamedTypeSymbol;

            if (namedType is not null && IsComplexDocumentType(namedType) && !seen.Contains(namedType, SymbolEqualityComparer.Default))
            {
                builder.Append(indent).Append("public static class ").Append(memberName).AppendLine();
                builder.Append(indent).AppendLine("{");
                builder.Append(indent).Append("    private static readonly global::Stateful.JsonObjectPath<").Append(documentType).Append("> Path = ").Append(pathVariable).Append(".Object(\"").Append(Escape(jsonName)).AppendLine("\");");
                builder.AppendLine();
                EmitMembers(builder, namedType, documentType, "Path", indent + "    ", seen.Add(namedType));
                builder.Append(indent).AppendLine("}");
                builder.AppendLine();
            }
            else
            {
                builder.Append(indent)
                    .Append("public static readonly global::Stateful.JsonPath<")
                    .Append(documentType)
                    .Append(", ")
                    .Append(propertyType)
                    .Append("> ")
                    .Append(memberName)
                    .Append(" = ")
                    .Append(pathVariable)
                    .Append(".Field<")
                    .Append(propertyType)
                    .Append(">(\"")
                    .Append(Escape(jsonName))
                    .AppendLine("\");");
            }
        }
    }

    private static IEnumerable<IPropertySymbol> GetSerializableProperties(INamedTypeSymbol type)
        => type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(property =>
                !property.IsStatic &&
                property.DeclaredAccessibility == Accessibility.Public &&
                property.GetMethod is not null &&
                !property.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonIgnoreAttribute"));

    private static ITypeSymbol UnwrapNullable(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable)
        {
            return nullable.TypeArguments[0];
        }

        return type;
    }

    private static bool IsComplexDocumentType(INamedTypeSymbol type)
    {
        if (type.SpecialType != SpecialType.None || type.TypeKind is TypeKind.Enum or TypeKind.Delegate)
        {
            return false;
        }

        if (type.ContainingNamespace.ToDisplayString().StartsWith("System", StringComparison.Ordinal))
        {
            return false;
        }

        return GetSerializableProperties(type).Any();
    }

    private static string GetJsonName(IPropertySymbol property)
    {
        foreach (var attribute in property.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonPropertyNameAttribute" &&
                attribute.ConstructorArguments.Length == 1 &&
                attribute.ConstructorArguments[0].Value is string name)
            {
                return name;
            }
        }

        return ToCamelCase(property.Name);
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrEmpty(value) || char.IsLower(value[0]))
        {
            return value;
        }

        if (value.Length == 1)
        {
            return value.ToLowerInvariant();
        }

        return char.ToLowerInvariant(value[0]) + value.Substring(1);
    }

    private static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "_";
        }

        var builder = new StringBuilder(value.Length);

        for (var i = 0; i < value.Length; i++)
        {
            var ch = value[i];
            builder.Append(i == 0
                ? SyntaxFacts.IsIdentifierStartCharacter(ch) ? ch : '_'
                : SyntaxFacts.IsIdentifierPartCharacter(ch) ? ch : '_');
        }

        var identifier = builder.ToString();
        return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : "@" + identifier;
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
